.PRECIOUS: $(OBJ_DIR)/%.o

OBJS = $(CXXSRCS:.cpp=.o) 
DST_OBJS = $(addprefix $(OBJ_DIR)/, $(OBJS))
TARGETS = $(OBJ_DIR)/$(TARGET).elf

all:: $(TARGETS)
	echo $(TARGETS)

$(OBJ_DIR)/%.elf: $(DST_OBJS)
	$(CC) $^ $(LDFLAGS) -o $@

$(OBJ_DIR)/%.o: %.cpp
	mkdir -p "$(OBJ_DIR)/`dirname $<`"
	$(CC) $(CXXFLAGS) -o $@ -c $<
