CC=g++-12

CXXFLAGS = \
	-O2 \
	-Wall \
	-Wextra \
	-Wno-ignored-qualifiers \
	-Wno-parentheses \
	-Wno-redundant-move \
	-Wno-unused-parameter \
	-Wunreachable-code \
	-g \
	-std=c++20 \
	-DTRACE_ENABLED

LDFLAGS = \
	-lstdc++

ifdef SANITIZE
	CXXFLAGS += -fsanitize=address
	CXXFLAGS += -fsanitize=undefined
	LDFLAGS += -fsanitize=address
	LDFLAGS += -fsanitize=undefined
endif
